if: (branch =~ ^master$|^development$|^release) AND !(commit_message =~ /(\[skip publish])/)

language: python
group: stable
dist: trusty
os: linux
sudo: required
services:
- docker

cache: pip

script: |-
  set -e
  if [ "master" == "${TRAVIS_BRANCH}" ]; then
    for env_value in $(compgen -v |grep '.*_PRODUCTION$'); do
      eval export ${env_value%_PRODUCTION}="${!env_value}"
    done
    export ENVIRONMENT="production"
  else
    for env_value in $(compgen -v |grep '.*_DEVELOPMENT$'); do
      eval export ${env_value%_DEVELOPMENT}="${!env_value}"
    done
    export ENVIRONMENT="staging"
  fi

  export IMAGE_INSTALLER=installer

  docker build -t ${IMAGE_INSTALLER} \
    --target installer \
    --build-arg GITHUB_TOKEN=${CI_GITHUB_TOKEN} \
    .

deploy:
# Update release version
- provider: script
  script: |-
    docker run --rm
      -v /home/travis/.ssh/id_rsa:/root/.ssh/id_rsa
      -v ${PWD}.git:/dir/.git
      $IMAGE_INSTALLER
      bash -c
      "yarn
      && git config user.email 'builds@travis-ci.org'
      && git config user.name 'Travis CI'
      && git checkout -B ${TRAVIS_BRANCH}
      && yarn release"
  on:
    branch:
      - master
